server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservas
    username: your-username
    password: your-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework: INFO
    br.com.reservas: DEBUG
